"""Shared build harness for the offline synthesis stages S3+.

S2 keeps its own frozen builder (``build_dataset.py``) so its locked result stays
reproducible byte-for-byte. Every later stage (S3, S5, S6) is generated by its own
builder module (``build_s3.py``, ...) on top of this harness, so the per-stage code
stays self-contained while the generic plumbing (worker loop, statistic guard,
manifest/config/index/log writers) is written once.

A stage module must expose:

- ``assign(sources, seed) -> dict[str, str]``
    deterministic mapping from a source image path to its variant (condition).
- ``sample(rng, variant, shape) -> (names, params)``
    op names and a JSON-loggable parameter dict, sampled from the seeded ``rng``.
- ``apply(img, names, params, rng) -> np.ndarray``
    geometry-preserving transform returning a float image.
- ``describe(names, params) -> str``
    a stable, human-readable parameter string for the audit log.

The generated dataset is ``A clear (referenced from bdd_src) + B transformed`` so
S1 (A + B, all clear) remains the exact control (``PROJECT.md`` §5).
"""

from __future__ import annotations

import csv
import importlib
import json
import shutil
import sys
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from common import CONFIGS_DIR, SPLITS_DIR, UNIFIED_CLASSES, ensure_dir  # noqa: E402
from synth import common as C  # noqa: E402

# stage -> importable module path (extend as S5/S6 are added).
MODULE_BY_STAGE: dict[str, str] = {"s3": "synth.weather", "s5": "synth.physics"}

LOG_COLUMNS = ("source", "image", "label", "stage", "condition", "ops", "seed", "attempt")

# If a source is usable but the transform makes it near-black/white or near-constant,
# resample (deterministically) up to this many times before accepting.
MAX_STAT_ATTEMPTS = 8

# A transformed image must not be near-black/white or near-constant...
DEGENERATE_MIN_MEAN = 5.0
DEGENERATE_MAX_MEAN = 250.0
DEGENERATE_MIN_STD = 10.0

# ...unless the source itself is low-signal (e.g. a tunnel frame in the clear/daytime
# pool): a dark source darkened further cannot be "rescued". Such sources are exempt
# from the guard and recorded as source-degenerate. The inspector uses the same rule.
SOURCE_MIN_MEAN = 20.0
SOURCE_MIN_STD = 10.0


def stat_ok(image: np.ndarray) -> bool:
    """Usable-image heuristic: mean in [5, 250] and std >= 10."""
    return (
        DEGENERATE_MIN_MEAN <= float(image.mean()) <= DEGENERATE_MAX_MEAN
        and float(image.std()) >= DEGENERATE_MIN_STD
    )


def source_usable(image: np.ndarray) -> bool:
    """Whether a source has enough signal for a transform to be meaningfully checked."""
    return float(image.mean()) >= SOURCE_MIN_MEAN and float(image.std()) >= SOURCE_MIN_STD


def stage_module(stage: str):
    """Import and return the registered module for a stage."""
    if stage not in MODULE_BY_STAGE:
        raise NotImplementedError(f"stage '{stage}' has no module (have: {sorted(MODULE_BY_STAGE)})")
    return importlib.import_module(MODULE_BY_STAGE[stage])


def write_dataset_config(
    dataset_name: str,
    root: Path,
    train_manifest: Path,
    val_manifest: Path,
) -> Path:
    """Write an Ultralytics dataset YAML referencing manifest files."""
    names = "\n".join(f"  {i}: {n}" for i, n in UNIFIED_CLASSES.items())
    content = (
        f"path: {root}\n"
        f"train: {train_manifest}\n"
        f"val: {val_manifest}\n"
        f"nc: {len(UNIFIED_CLASSES)}\n"
        f"names:\n{names}\n"
    )
    path = CONFIGS_DIR / f"{dataset_name}.yaml"
    path.write_text(content, encoding="utf-8")
    return path


def _process_one(task: tuple[str, str, str, int, int, str]) -> tuple[dict, dict]:
    """Load one source image, apply its assigned variant, write image + label."""
    source, condition, out_images, seed, jpeg_quality, stage = task
    module = stage_module(stage)
    out_images = Path(out_images)
    label_dir = out_images.parent / "labels"

    img = cv2.imread(source, cv2.IMREAD_COLOR)
    if img is None:
        raise FileNotFoundError(f"could not read image: {source}")

    source_ok = source_usable(img)
    attempt = 0
    while True:
        extra = () if attempt == 0 else (attempt,)
        rng = np.random.default_rng(C.stable_seed(Path(source).name, stage, seed, condition, *extra))
        names, params = module.sample(rng, condition, img.shape)
        degraded = module.apply(img, names, params, rng)
        degraded_u8 = np.rint(degraded).astype(np.uint8)
        if source_ok and not stat_ok(degraded_u8) and attempt < MAX_STAT_ATTEMPTS:
            attempt += 1
            continue
        break

    name = Path(source).name
    out_image = out_images / name
    cv2.imwrite(str(out_image), degraded_u8, [cv2.IMWRITE_JPEG_QUALITY, jpeg_quality])

    out_label = label_dir / f"{Path(source).stem}.txt"
    shutil.copy2(C.label_path_for(source), out_label)

    image_seed = C.stable_seed(Path(source).name, stage, seed, condition, *extra)
    record = {
        "source": source,
        "image": str(out_image),
        "label": str(out_label),
        "stage": stage,
        "condition": condition,
        "ops": list(names),
        "params": params,
        "seed": image_seed,
        "attempt": attempt,
    }
    log_row = {
        "source": source,
        "image": str(out_image),
        "label": str(out_label),
        "stage": stage,
        "condition": condition,
        "ops": module.describe(names, params),
        "seed": image_seed,
        "attempt": attempt,
    }
    return record, log_row


def run_build(stage: str, limit: int | None, seed: int, jobs: int, jpeg_quality: int) -> Path:
    """Build the stage dataset and return its root."""
    module = stage_module(stage)
    dataset_name = f"bdd_{stage}" if not limit else f"bdd_{stage}_smoke"
    root = C.dataset_root(dataset_name)
    images_dir = ensure_dir(root / "images")
    ensure_dir(root / "labels")

    a_clear, b_source = C.source_halves(seed)
    if not limit:
        C.write_halves(a_clear, b_source)

    a_sel = a_clear if not limit else a_clear[:limit]
    b_sel = b_source if not limit else b_source[:limit]
    assignment = module.assign(b_sel, seed)

    tasks = [
        (src, assignment[src], str(images_dir), seed, jpeg_quality, stage)
        for src in b_sel
    ]
    print(f"[build] {dataset_name}: transforming {len(tasks)} B images, A referenced={len(a_sel)}")

    records: list[dict] = []
    log_rows: list[dict] = []
    if jobs > 1:
        with ProcessPoolExecutor(max_workers=jobs) as pool:
            for i, (record, log_row) in enumerate(pool.map(_process_one, tasks), 1):
                records.append(record)
                log_rows.append(log_row)
                if i % 500 == 0:
                    print(f"[build]   {i}/{len(tasks)}")
    else:
        for i, task in enumerate(tasks, 1):
            record, log_row = _process_one(task)
            records.append(record)
            log_rows.append(log_row)
            if i % 500 == 0:
                print(f"[build]   {i}/{len(tasks)}")

    records.sort(key=lambda r: r["source"])
    log_rows.sort(key=lambda r: r["source"])

    manifest = SPLITS_DIR / f"{dataset_name}_train.txt"
    manifest.write_text("\n".join(a_sel + [r["image"] for r in records]) + "\n", encoding="utf-8")

    conditions_csv = SPLITS_DIR / f"{dataset_name}_conditions.csv"
    with conditions_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(("source", "condition"))
        writer.writerows((r["source"], r["condition"]) for r in records)

    (root / "index.json").write_text(json.dumps(records, indent=2), encoding="utf-8")
    with (root / "synthesis_log.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=LOG_COLUMNS)
        writer.writeheader()
        writer.writerows(log_rows)

    config = write_dataset_config(dataset_name, root, manifest, SPLITS_DIR / "bdd_src_val.txt")
    print(f"[build] images -> {images_dir}")
    print(f"[build] manifest -> {manifest} ({len(a_sel) + len(records)} entries)")
    print(f"[build] conditions -> {conditions_csv}")
    print(f"[build] config -> {config}")
    return root
